# This file was generated by GoReleaser. DO NOT EDIT.
cask "bigtui" do
  version "1.0.0"

  on_macos do
    on_arm do
      sha256 "007b936d702ff9434aa87771360e4b124db7927621e6a230bd2af9b37baeb655"
      url "https://github.com/0xjrr/bigtui/releases/download/v#{version}/bigtui_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "606db7c5472fa7d9216a683bb527a47110b4b6d9d823ab3a9abcae9839ccbd07"
      url "https://github.com/0xjrr/bigtui/releases/download/v#{version}/bigtui_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6182735913f82e1ed5fdc08ca659b4fabd7612be48e21b152072cabb2c8e37a7"
      url "https://github.com/0xjrr/bigtui/releases/download/v#{version}/bigtui_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "76a3a044dd38cd3709159e8f1c7e78a0ac5460c7481e6d8f0880155763e42887"
      url "https://github.com/0xjrr/bigtui/releases/download/v#{version}/bigtui_#{version}_linux_amd64.tar.gz"
    end
  end

  name "bigtui"
  desc "Keyboard-first terminal workspace for querying BigQuery"
  homepage "https://github.com/0xjrr/bigtui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bigtui"

  # No zap stanza required
end
