# This file was generated by GoReleaser. DO NOT EDIT.
cask "bigtui" do
  version "1.0.1"

  on_macos do
    on_arm do
      sha256 "455206abc0598941f486daab845a9bacd8e92ae22b9dc469c6cd3662bebacf95"
      url "https://github.com/0xjrr/bigtui/releases/download/v#{version}/bigtui_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d08a5b98a2c62e6d41f952abb1973d770a7af163e90df0f15ac8c0f2e9fafe73"
      url "https://github.com/0xjrr/bigtui/releases/download/v#{version}/bigtui_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d4d0af1e8935141aee8735d90252bbe8e6c78071e6356f3c2389e3c42ddc6be1"
      url "https://github.com/0xjrr/bigtui/releases/download/v#{version}/bigtui_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3e882b5d69fa5d2674bb98e7b42195d3dccd4368a29e57aef7f2769e3f2792f6"
      url "https://github.com/0xjrr/bigtui/releases/download/v#{version}/bigtui_#{version}_linux_amd64.tar.gz"
    end
  end

  name "bigtui"
  desc "Keyboard-first terminal workspace for querying BigQuery"
  homepage "https://github.com/0xjrr/bigtui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bigtui"

  # No zap stanza required
end
